### PR TITLE
Add eng language

### PR DESCRIPTION
**Pull request by delirus18**

### CODE REVIEW

**Comment by hujesse83** [comment]
这样是不是中文就没了

**Review by thinhnguyenhcm — APPROVED** [review]

**Comment by GeorgeII** [comment]
It will be so awesome if you add English!

**Comment by demib72** [comment]
> 这样是不是中文就没了

Looking at this, that is what it looks like. I noticed there are translation toml files. If they work, couldn't those just be expanded to include more of the site?

**Comment by vaxilu** [comment]
翻译文件的使用示例可以查看以下文件

https://github.com/vaxilu/x-ui/blob/97020a82bcae345e92bf042c9392b1640f317f00/web/html/login.html#L55

https://github.com/vaxilu/x-ui/blob/97020a82bcae345e92bf042c9392b1640f317f00/web/translation/translate.en_US.toml#L3

https://github.com/vaxilu/x-ui/blob/97020a82bcae345e92bf042c9392b1640f317f00/web/translation/translate.zh_Hans.toml#L3

https://github.com/vaxilu/x-ui/blob/97020a82bcae345e92bf042c9392b1640f317f00/web/translation/translate.zh_Hant.toml#L3

你需要按照严格的格式来进行翻译，这样才能支持多语言，这可能需要一些html知识

**Comment by love768952693** [comment]
借楼反馈个问题，0.32 版本  vless+xtls-rprx-direct  无法使用，连不上，其它协议模式又可以。。。。

**Comment by love768952693** [comment]
> 翻译文件的使用示例可以查看以下文件
> 
> https://github.com/vaxilu/x-ui/blob/97020a82bcae345e92bf042c9392b1640f317f00/web/html/login.html#L55
> 
> https://github.com/vaxilu/x-ui/blob/97020a82bcae345e92bf042c9392b1640f317f00/web/translation/translate.en_US.toml#L3
> 
> https://github.com/vaxilu/x-ui/blob/97020a82bcae345e92bf042c9392b1640f317f00/web/translation/translate.zh_Hans.toml#L3
> 
> https://github.com/vaxilu/x-ui/blob/97020a82bcae345e92bf042c9392b1640f317f00/web/translation/translate.zh_Hant.toml#L3
> 
> 你需要按照语言的格式来进行翻译，这样才能支持多种，这可能需要一些 HTML 知识

借楼反馈个问题，0.32版本vless+xtls-rprx-direct 无法使用，又连不上，其他协议模式可以。。。

**Comment by merura** [comment]
I made a temporary solution to the problem. 
My code is to patch the x-ui source code by translating it into English
If you are only interested in the English version of x-ui, you can download it from my repository
https://github.com/tshipenchko/x-ui-en/

**Comment by Onair-santa** [comment]
> I made a temporary solution to the problem. My code is to patch the x-ui source code by translating it into English If you are only interested in the English version of x-ui, you can download it from my repository https://github.com/tshipenchko/x-ui-en/

can you help with fail2ban jail settings for x-ui web interface?

**Pull request closed without merging**
