### PR TITLE
Translate All Important things to English.

### PR DESCRIPTION
**Pull request by Msameim181**
Translate with Google translator (Zh-cn to en).
All HTML, go and bash scripts.
let me know if anything missing

### CODE REVIEW

**Review by TheMajidHeydari — APPROVED** [review]
its can be helpful.

**Comment by FranzKafkaYu** [comment]
> Translate with Google translator (Zh-cn to en). All HTML, go and bash scripts. let me know if anything missing

@Msameim181 this method is not good,you must find some way to keep Chinese/ English both,I have completed this work,if you need this Version you can check my git repository.

**Comment by proaref** [comment]
> Translate with Google translator (Zh-cn to en). All HTML, go and bash scripts. let me know if anything missing

hi my friend i have question how can i import users with all setting and export to new server?

**Comment by FranzKafkaYu** [comment]
> > Translate with Google translator (Zh-cn to en). All HTML, go and bash scripts. let me know if anything missing
> 
> hi my friend i have question how can i import users with all setting and export to new server?

@proaref Just export /etc/x-ui/x-ui.db to another server with the same directory.

**Comment by Msameim181** [comment]
> > Translate with Google translator (Zh-cn to en). All HTML, go and bash scripts. let me know if anything missing
> 
> @Msameim181 this method is not good,you must find some way to keep Chinese/ English both,I have completed this work,if you need this Version you can check my git repository.

Excellent, I Was thinking about general people using EN, that's why I didn't hold Chinese. 
If you did so, you did a good job. Maybe you could improve UI/UX a bit more and it would more fun.
If you need any assistance, let me know.
Cheers to you. :)

**Pull request closed without merging**
