### PR TITLE
Add vless muilti client configuration support on same port

### PR DESCRIPTION
**Pull request by awawa42**
增加了在同端口使用多个UUID的VLESS配置
对应配置文件

```  json
    {
      "listen": null,
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "uuid1",
            "flow": "xtls-rprx-direct"
          },
          {
            "id": "uuid2",
            "flow": "xtls-rprx-direct"
          }
        ],
        "decryption": "none",
        "fallbacks": []
      }
```

### CODE REVIEW

**Review by blackpaper666 — APPROVED** [review]

**Comment by WikiHacker** [comment]
inbound_info.html do we need to update anything here? we cannot see the information.  ( only first uuid, how to display others?

image
image

**Comment by WikiHacker** [comment]
> 增加了在同端口使用多个UUID的VLESS配置 对应配置文件
> 
> ```json
>     {
>       "listen": null,
>       "port": 443,
>       "protocol": "vless",
>       "settings": {
>         "clients": [
>           {
>             "id": "uuid1",
>             "flow": "xtls-rprx-direct"
>           },
>           {
>             "id": "uuid2",
>             "flow": "xtls-rprx-direct"
>           }
>         ],
>         "decryption": "none",
>         "fallbacks": []
>       }
> ```

inbound_info.html do we need to update anything here? we cannot see the information.  ( only first uuid, how to display others?

image
image

**Comment by Pacio** [comment]
想给shadowsocks添加新的2022的加密方式怎么修改啊？求分享

**Comment by sbh96** [comment]
Please confirm this request. We desperately need free internet in Iran. Unfortunately, we cannot create multiple users on same port
The only protocol that responds to government filtering in Iran is v2ray

**Comment by Pacio** [comment]
> Please confirm this request. We desperately need free internet in Iran. Unfortunately, we cannot create multiple users on same port The only protocol that responds to government filtering in Iran is v2ray

https://github.com/FranzKafkaYu/x-ui
Hope it can help you, this project has the functions you need

**Comment by sbh96** [comment]
> > Please confirm this request. We desperately need free internet in Iran. Unfortunately, we cannot create multiple users on same port The only protocol that responds to government filtering in Iran is v2ray
> 
> https://github.com/FranzKafkaYu/x-ui Hope it can help you, this project has the functions you need

Thanks for your fast reply 
This fork is support multiple user in same port?

**Comment by Pacio** [comment]
> > > Please confirm this request. We desperately need free internet in Iran. Unfortunately, we cannot create multiple users on same port The only protocol that responds to government filtering in Iran is v2ray
> > 
> > 
> > https://github.com/FranzKafkaYu/x-ui Hope it can help you, this project has the functions you need
> 
> Thanks for your fast reply This fork is support multiple user in same port?

sure

**Comment by bashir59** [comment]
hi,
How can we backup user's Account and restore it on another server?

**Comment by mdhosseini** [comment]
hi
need just one user can connect in a same time. 
in this vpn many user can connect to one inbound (user) in the same time and are multi user connect.
i need to just one user can connect in same time by id and other user have not access to connect.
please tell me how can i set it.

**Comment by meysam98** [comment]
你好
在这个 vpn 中，多用户可以同时连接到一个入站。
我只需要一个用户可以同时连接到 UID，而其他用户无权连接。
请告诉我如何设置它。

**Comment by proaref** [comment]
> > > > Please confirm this request. We desperately need free internet in Iran. Unfortunately, we cannot create multiple users on same port The only protocol that responds to government filtering in Iran is v2ray
> > > 
> > > 
> > > https://github.com/FranzKafkaYu/x-ui Hope it can help you, this project has the functions you need
> > 
> > 
> > Thanks for your fast reply This fork is support multiple user in same port?
> 
> sure

hi my friend i have question how can i import users with all setting and export to new server?

**Comment by proaref** [comment]
> Please confirm this request. We desperately need free internet in Iran. Unfortunately, we cannot create multiple users on same port The only protocol that responds to government filtering in Iran is v2ray

hi my friend i have question how can i import users with all setting and export to new server? ( im from iran goverment block ips )

**Comment by Pacio** [comment]
> > Please confirm this request. We desperately need free internet in Iran. Unfortunately, we cannot create multiple users on same port The only protocol that responds to government filtering in Iran is v2ray
> 
> hi my friend i have question how can i import users with all setting and export to new server? ( im from iran goverment block ips )

Just back up this file ( /etc/x-ui/x-ui.db ) , and then overwrite it directly after building the project on the new server

**Comment by Pacio** [comment]
> hi, How can we backup user's Account and restore it on another server?
Just back up this file ( /etc/x-ui/x-ui.db ) , and then overwrite it directly after building the project on the new server

**Comment by soheil-1981** [comment]
Hello friends, can anyone guide me, I install win 7-64 in nekoray software,
I activate vpn mode, it doesn't activate, it gives me several tls errors,
I'm grateful for your help.
-- 
Sent from Gmail Mobile

**Comment by miladrajabi2002** [comment]
> > > > Please confirm this request. We desperately need free internet in Iran. Unfortunately, we cannot create multiple users on same port The only protocol that responds to government filtering in Iran is v2ray
> > > 
> > > 
> > > https://github.com/FranzKafkaYu/x-ui Hope it can help you, this project has the functions you need
> > 
> > 
> > Thanks for your fast reply This fork is support multiple user in same port?
> 
> sure

don`t have this option and is it fake

**Comment by Ramintn** [comment]
Hi
Yesterday xray 1.8 was released,, but when i switch version to 1.8 in xui panel,,the panel stops working and go to error condition,,
Why?
When i turn off all inbounds it says running,,when i turn on one of inbounds it go to error status,,why??
But no problem with version 1.7.5
Please help

**Pull request closed without merging**
