### PR TITLE
Multi user inbound (Vless , Vmess)

### PR DESCRIPTION
**Pull request by hossinasaadi**
**-  multi-user feature added**
**- generate QR for more than 1 clients**

Screenshot from 2022-11-01 14-21-00

### **install :**
**[install](https://github.com/hossinasaadi/x-ui)**

### CODE REVIEW

**Comment by AliDeV7** [comment]
Multi-user on Same port?

**Comment by hossinasaadi** [comment]
> Multi-user on Same port?

yes

**Comment by AliDeV7** [comment]
Oww Thanks :)

**Comment by miladrajabi2002** [comment]
It is useless because it does not show traffic

**Comment by proshir** [comment]
Thank you for all your efforts in this regard
You are a hero for the Iranian people in this difficult situation

**Comment by proshir** [comment]
> It is useless because it does not show traffic

If you want you can write this yourself. You are the one who goes everywhere and says this is a lie and useless
But thank you for your criticism. If possible, please add this because it is very valuable
Thanks.

**Comment by proshir** [comment]
Could you teach me how i can build the project myself with go build main.go . When I run this command, it gives an error and it says ' embeded error finding packages'

**Comment by iXria** [comment]
hi why it dont works in vless for me is there another setting i should do ?

**Comment by hossinasaadi** [comment]
> hi why it dont works in vless for me is there another setting i should do ?

no it works properly. clear browser cache may cause of that

**Comment by Tigerevenge** [comment]
could you add ip limits for this too?

**Comment by rahman8521** [comment]
Hi .
thank you very much for your efforts
If you can, set an IP limit for each user(UUID) and an expiration date. It would be great

Edit:
In fact, IP limite is not important. In order to avoid server blocking in Iran, we have to use tunnel or CDN
expiration date is more important for every user than the IP limit

**Comment by iXria** [comment]
> > hi why it dont works in vless for me is there another setting i should do ?
> 
> no it works properly. clear browser cache may cause of that

Even i add log into related section and clear cache its not work for me in vless protocol i just can see this for vmess and even i ِDont see multiuser QR section.
Please guide me thanks.

**Comment by hossinasaadi** [comment]
> > > hi why it dont works in vless for me is there another setting i should do ?
> > 
> > 
> > no it works properly. clear browser cache may cause of that
> 
> Even i add log into related section and clear cache its not work for me in vless protocol i just can see this for vmess and even i ِDont see multiuser QR section. Please guide me thanks.

hi, I update to install.sh
install it again

**Comment by iXria** [comment]
> > > > hi why it dont works in vless for me is there another setting i should do ?
> > > 
> > > 
> > > no it works properly. clear browser cache may cause of that
> > 
> > 
> > Even i add log into related section and clear cache its not work for me in vless protocol i just can see this for vmess and even i ِDont see multiuser QR section. Please guide me thanks.
> 
> hi, I update to install.sh install it again

Thank you for effort and help community
I updated and
Now multi QR and user added but ip limit dont show anymore in all protocol section even vmess 
Please check it thank you.

**Comment by mory** [comment]
> I updated and Now multi QR and user added but ip limit dont show anymore in all protocol section even vmess Please check it.

Cuz Its just on another branch...not merged with main branch that has ip limit codes

**Comment by iXria** [comment]
> 

So what i should do now?

**Comment by a7one** [comment]
> > > > > hi why it dont works in vless for me is there another setting i should do ?
> > > > 
> > > > 
> > > > no it works properly. clear browser cache may cause of that
> > > 
> > > 
> > > Even i add log into related section and clear cache its not work for me in vless protocol i just can see this for vmess and even i ِDont see multiuser QR section. Please guide me thanks.
> > 
> > 
> > hi, I update to install.sh install it again
> 
> Thank you for effort and help community I updated and Now multi QR and user added but ip limit dont show anymore in all protocol section even vmess Please check it thank you.

do hard refresh with ctrl+f5

**Comment by iXria** [comment]
> > > > > > hi why it dont works in vless for me is there another setting i should do ?
> > > > > 
> > > > > 
> > > > > no it works properly. clear browser cache may cause of that
> > > > 
> > > > 
> > > > Even i add log into related section and clear cache its not work for me in vless protocol i just can see this for vmess and even i ِDont see multiuser QR section. Please guide me thanks.
> > > 
> > > 
> > > hi, I update to install.sh install it again
> > 
> > 
> > Thank you for effort and help community I updated and Now multi QR and user added but ip limit dont show anymore in all protocol section even vmess Please check it thank you.
> 
> do hard refresh with ctrl+f5

I do it and also i clear cache but still not working :(

**Comment by koloner** [comment]
Hi Thanks you for effort.how add api for edit inboard information?

**Comment by iXria** [comment]
> 

Please someone help me i really need ip limit option

**Comment by proshir** [comment]
> Hi Thanks you for effort.how add api for edit inboard information?

what do you mean ? If you see the network element section of the browser, you will understand how it uses API.
image

**Comment by koloner** [comment]
Yes.i know but i cannt connect with other server to x-ui.
error : Failed to connect to port Connection refused

**Comment by miladrajabi2002** [comment]
Since it does not show the consumption, nor can the expiration date be set, and the remark is not useful

**Comment by niiiii** [comment]
hi can u make web api for client account detail like how much they use their traffic
and another question where is the data base save after installation like user keys

**Comment by proshir** [comment]
> Yes.i know but i cannt connect with other server to x-ui.
> error : Failed to connect to port Connection refused

maybe you have to set firewall like ufw

**Comment by amihos** [comment]
Hi and thank you very much for your great job. Can you make api for adding, removing, editing users remotely without logging in the panel?

**Comment by DanialSaebi** [comment]
What is the problem with Hamrahe-Avval uploading on vless ws?

**Comment by sbh96** [comment]
@DanialSaebi > 

You must use secend server in iran middle of your server located in out side of country

**Comment by koloner** [comment]
> > Yes.i know but i cannt connect with other server to x-ui.
> > error : Failed to connect to port Connection refused
> 
> maybe you have to set firewall like ufw

ufw work.Test Code in online editor is true but in the my server have problem.

**Comment by DanialSaebi** [comment]
@sbh96 

I used cloudflare to proxy my server ip address 
It works on irancell and other ISP's
But hamrahe-avval uploading is weak!!

I used middle server before and my ip has been blocked!!
The best way is a CDN connecting to your server

**Comment by wulfric93** [comment]
Almost all ISP's here in iran blocked Both VMESS and VLESS With And Without TLS , starting from appromily approximately from 10 AM Iran, Tehran Local Time, is there any alternative to bypass this huge perturbation ? anyone Know ?
MCI,Irancell,Rightel,ADSL,TD-LTE

**Comment by proshir** [comment]
> > > Yes.i know but i cannt connect with other server to x-ui.
> > > error : Failed to connect to port Connection refused
> > 
> > 
> > maybe you have to set firewall like ufw
> 
> ufw work.Test Code in online editor is true but in the my server have problem.

be careful If you use Cloudflare, you can have only a few open ports:
https://developers.cloudflare.com/fundamentals/get-started/reference/network-ports/

**Comment by moin110x** [comment]
@arsoltani72 yes, my 4 servers blocked, even  with trojan xtls ; the only thing i havent tried is to only make 1 trojan account and share it to all users so they all be connected to same port and less connections will be created to server so the iran smart ip blocker wont figure it out , hopefully :)

**Comment by DanialSaebi** [comment]
Thank you bro

**Comment by wulfric93** [comment]
> @arsoltani72 yes, my 4 servers blocked, even with trojan xtls ; the only thing i havent tried is to only make 1 trojan account and share it to all users so they all be connected to same port and less connections will be created to server so the iran smart ip blocker wont figure it out , hopefully :)

I've bought VPS Server From Hetzner directly and this datacener has feuture named "Floating IP" and Its somehow can elimiate the need of another server in the middle, its like public ip and you can change that ip when ip blocked by iran Infrastructure organization. 

but i've encounter weak upload via MCI and i presume the only way to skiping it is to use iranian VPS and tunnel it to outside VPS Floating Ip address .

**Comment by DanialSaebi** [comment]
> > @arsoltani72 yes, my 4 servers blocked, even with trojan xtls ; the only thing i havent tried is to only make 1 trojan account and share it to all users so they all be connected to same port and less connections will be created to server so the iran smart ip blocker wont figure it out , hopefully :)
> 
> I've bought VPS Server From Hetzner directly and this datacener has feuture named "Floating IP" and Its somehow can elimiate the need of another server in the middle, its like public ip and you can change that ip when ip blocked by iran Infrastructure organization.
> 
> but i've encounter weak upload via MCI and i presume the only way to skiping it is to use iranian VPS and tunnel it to outside VPS Floating Ip address .

Use arvancloud cdn to avoid filtering

you can get free domain on freenom.com with usa vpn only

**Comment by a7one** [comment]
> > @arsoltani72 yes, my 4 servers blocked, even with trojan xtls ; the only thing i havent tried is to only make 1 trojan account and share it to all users so they all be connected to same port and less connections will be created to server so the iran smart ip blocker wont figure it out , hopefully :)
> 
> I've bought VPS Server From Hetzner directly and this datacener has feuture named "Floating IP" and Its somehow can elimiate the need of another server in the middle, its like public ip and you can change that ip when ip blocked by iran Infrastructure organization.
> 
> but i've encounter weak upload via MCI and i presume the only way to skiping it is to use iranian VPS and tunnel it to outside VPS Floating Ip address .

if you server blocked by iran you can also change your primary ip in hetzner you dont have to use floating ip

**Comment by wulfric93** [comment]
> > > @arsoltani72 yes, my 4 servers blocked, even with trojan xtls ; the only thing i havent tried is to only make 1 trojan account and share it to all users so they all be connected to same port and less connections will be created to server so the iran smart ip blocker wont figure it out , hopefully :)
> > 
> > 
> > I've bought VPS Server From Hetzner directly and this datacener has feuture named "Floating IP" and Its somehow can elimiate the need of another server in the middle, its like public ip and you can change that ip when ip blocked by iran Infrastructure organization.
> > but i've encounter weak upload via MCI and i presume the only way to skiping it is to use iranian VPS and tunnel it to outside VPS Floating Ip address .
> 
> if you server blocked by iran you can also change your primary ip in hetzner you dont have to use floating ip

How ?

**Comment by wulfric93** [comment]
> > > @arsoltani72 yes, my 4 servers blocked, even with trojan xtls ; the only thing i havent tried is to only make 1 trojan account and share it to all users so they all be connected to same port and less connections will be created to server so the iran smart ip blocker wont figure it out , hopefully :)
> > 
> > 
> > I've bought VPS Server From Hetzner directly and this datacener has feuture named "Floating IP" and Its somehow can elimiate the need of another server in the middle, its like public ip and you can change that ip when ip blocked by iran Infrastructure organization.
> > but i've encounter weak upload via MCI and i presume the only way to skiping it is to use iranian VPS and tunnel it to outside VPS Floating Ip address .
> 
> Use arvancloud cdn to avoid filtering
> 
> you can get free domain on freenom.com with usa vpn only

Really ? I didn't knew it , thanks , I'll check it

**Comment by wulfric93** [comment]
> > > @arsoltani72 yes, my 4 servers blocked, even with trojan xtls ; the only thing i havent tried is to only make 1 trojan account and share it to all users so they all be connected to same port and less connections will be created to server so the iran smart ip blocker wont figure it out , hopefully :)
> > 
> > 
> > I've bought VPS Server From Hetzner directly and this datacener has feuture named "Floating IP" and Its somehow can elimiate the need of another server in the middle, its like public ip and you can change that ip when ip blocked by iran Infrastructure organization.
> > but i've encounter weak upload via MCI and i presume the only way to skiping it is to use iranian VPS and tunnel it to outside VPS Floating Ip address .
> 
> if you server blocked by iran you can also change your primary ip in hetzner you dont have to use floating ip

thank you

**Comment by wulfric93** [comment]
> > > @arsoltani72 yes, my 4 servers blocked, even with trojan xtls ; the only thing i havent tried is to only make 1 trojan account and share it to all users so they all be connected to same port and less connections will be created to server so the iran smart ip blocker wont figure it out , hopefully :)
> > 
> > 
> > I've bought VPS Server From Hetzner directly and this datacener has feuture named "Floating IP" and Its somehow can elimiate the need of another server in the middle, its like public ip and you can change that ip when ip blocked by iran Infrastructure organization.
> > but i've encounter weak upload via MCI and i presume the only way to skiping it is to use iranian VPS and tunnel it to outside VPS Floating Ip address .
> 
> Use arvancloud cdn to avoid filtering
> 
> you can get free domain on [freenom.com](http://freenom.com) with usa vpn only

how can i configure arvan ?

**Comment by arsoltani72** [comment]
i couldnt able to use ArvanCloud CDN by setting up a DNS record with cloud service enabled 
and i dont know which ports are available to use in free plan in arvan
hope you can help me to solve this issue 
pm me in telegram please : https://t.me/CyberProofNetwork

**Comment by hamed98** [comment]
Thank you for adding this useful feature.
Is it possible to add this feature for trojan?
because i think trojan is more resist against blocking than vless.

**Comment by hamed98** [comment]
> i couldnt able to use ArvanCloud CDN by setting up a DNS record with cloud service enabled and i dont know which ports are available to use in free plan in arvan hope you can help me to solve this issue pm me in telegram please : https://t.me/CyberProofNetwork

you can use cloudflare DNS

**Comment by wulfric93** [comment]
does anyone  know how to backup inbound users ? and move databse on other vps ?

**Comment by amihos** [comment]
Just copy and move x-ui.db

**Comment by amihos** [comment]
> does anyone  know how to backup inbound users ? and move databse on other vps ?

Just copy and move x-ui.db

**Comment by wulfric93** [comment]
> 

i've tried that and after replace x-ui.db , new server x-ui fails to lunch

**Comment by arsoltani72** [comment]
> > does anyone  know how to backup inbound users ? and move databse on other vps ?
> 
> Just copy and move x-ui.db

tried and on another server x-ui failed to start

**Comment by arsoltani72** [comment]
2022/11/24 21:26:39 WARNING - client ip job err: truncate ./root/access.log: no such file or directory

**Comment by arsoltani72** [comment]
> 2022/11/24 21:26:39 WARNING - client ip job err: truncate ./root/access.log: no such file or directory

how to solve this problem @hossinasaadi

**Comment by wulfric93** [comment]
i have problem in ios 16 , phone just not transfer data by OneClick VPN 
is there any soultion ?

**Comment by LitenBuzzTh** [comment]
I installed @hossinasaadi 's fork of x-ui and the ip limit feature is awesome actually. loved it!
Only one recommendation : please add ip limiting feauture to **Trojan** also.
it would be a great help 💯

**Comment by wulfric93** [comment]
@hossinasaadi is there anyway to reflect given email address in qr-code in order to being able to distinguish each config from others?

**Comment by ashkan-moghadasi** [comment]
> Almost all ISP's here in iran blocked Both VMESS and VLESS With And Without TLS , starting from appromily approximately from 10 AM Iran, Tehran Local Time, is there any alternative to bypass this huge perturbation ? anyone Know ? MCI,Irancell,Rightel,ADSL,TD-LTE

Your IP has Blocked

**Pull request closed without merging**
